name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd app
        python manage.py test

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t $DOCKER_USERNAME/django-app:${{ github.sha }} .
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push $DOCKER_USERNAME/django-app:${{ github.sha }}

    - name: Update Kubernetes manifests
      run: |
        sed -i 's|image: seu-usuario/django-app:.*|image: ${{ secrets.DOCKER_USERNAME }}/django-app:${{ github.sha }}|' manifests/deployment.yaml
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add manifests/deployment.yaml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push